pipeline {
  environment {
    registry = "eknaprasath/nodejs-app"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
  agent any
  stages {
 //   stage('Cloning Git') {
 //     steps {
   //     git 'https://github.com/gustavoapolinario/microservices-node-example-todo-frontend.git'
     // }
   // }
   stage('Preparation') {
     steps {
	 checkout scm
   }
   }
	stage('test') {
	steps {
   //  nodejs(nodeJSInstallationName: 'nodejs') 
       sh 'npm audit fix'
       sh 'npm install --only=dev'
       sh 'npm audit fix'
       sh 'npm test'
       sh 'npm audit fix --force'
     }
	 }
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build registry + ":$BUILD_NUMBER"
        }
      }
    }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', dockerhub ) {
            dockerImage.push()
          }
        }
      }
    }
    stage('Remove Unused docker image') {
      steps{
        sh "docker rmi $registry:$BUILD_NUMBER"
      }
    }
  }
}
